name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/checkout@v3
      with:
        repository: openfl/lime
        path: _lime-git
        ref: 8.1.3

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5

    - name: Set HAXEPATH
      run: |
        echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

    - name: Install Haxe dependencies
      run: |
        haxelib install dox 1.6.0
        haxelib dev lime _lime-git

    - name: Build docs
      working-directory: _lime-git/docs
      run: |
        haxe build.hxml

    - name: Copy docs
      run: |
        mkdir api
        cp -a _lime-git/docs/pages/. api/

    # - name: Install dependencies
    #   run: |
    #     sudo apt-get install zopfli
    #     _scripts/install.sh

    - name: Install dependencies
      run: |
        _scripts/install.sh
    
    - name: Build site
      run: |
        _scripts/build.sh
    
    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-west-2
    
    # - name: Deploy to AWS
    #   run: |
    #     _scripts/deploy.sh
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        # The following lines assign commit authorship to the official
        # GH-Actions bot for deploys to `gh-pages` branch:
        # https://github.com/actions/checkout/issues/13#issuecomment-724415212
        # The GH actions bot is used by default if you didn't specify the two fields.
        # You can swap them out with your own user credentials.
        user_name: github-actions[bot]
        user_email: 41898282+github-actions[bot]@users.noreply.github.com